pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd frontend && npm install'
            }
        }
        stage('Unit Testing') {
            steps {
                sh 'cd frontend && npm run unit-test'
            }
        }
        stage('Unit Testing Report') {
            steps {
                sh 'cd frontend && npm run unit-test-report'
                publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage/lcov-report",
                        reportFiles: "index.html",
                        reportName: 'Unit Test Coverage Report'
                    ]

                    publishHTML target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: "./coverage",
                        reportFiles: "report.html",
                        reportName: 'Unit Test Report'
                    ]
            }
        }
        stage('Component Testing') {
            steps {
                sh 'cd frontend && npm run component-test'
            }
        }
        stage('Component Testing Report') {
            steps {
                sh 'cd frontend && npm run component-test-report'
            }
        }
        stage('End-To-End Testing') {
            steps {
                sh 'cd frontend && npm run e2e-test || exit 0'
            }
        }
        stage('Build') {
            steps {
                sh 'cd frontend && npm run build'
            }
        }
        stage('Deployment') {
            steps {
                echo '---------------------------- Deployment ----------------------------'
                // sh ''
            }
        }
    }
}